crowd_hydrology/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app import views, receive_sms

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.contrib import admin
from django.urls import path
from main_app import views, receive_sms, graphs

# Template Urls
app_name = 'main_app'

urlpatterns = [
    path('sms/', receive_sms.incoming_sms, name='sms'),
    path('', views.index, name='index'),
    path('generate-graphs/', graphs.generate, name='generate-graphs'),
    path('download/', views.download, name='download'),
    #path('user_login/', views.user_login, name='user_login')
]

main_app/models.py
from django.db import models
from django.utils import timezone
from localflavor.us.us_states import STATE_CHOICES

# Create your models here.

class Sponsor(models.Model):
    name = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='station_sponsor_pics', blank=True)
    website = models.URLField(blank=True)

    def __str__(self):
        return self.name

class Station(models.Model):
    id = models.CharField(max_length=200, primary_key=True, unique=True)
    name = models.CharField(max_length=200)
    station_pic = models.ImageField(upload_to='station_pics', blank=True)
    state = models.CharField(
        max_length=2,
        choices=STATE_CHOICES,
        default='MI',
    )
    loc_latitude = models.DecimalField(max_digits=9, decimal_places=6)
    loc_longitude = models.DecimalField(max_digits=9, decimal_places=6)
    upper_bound = models.FloatField()
    lower_bound = models.FloatField()

    WATER_BODY_TYPE_CHOICES = (
        ('BR', 'Brook'),
        ('CA', 'Cave'),
        ('CR', 'Creek'),
        ('LA', 'Lake'),
        ('PO', 'Pond'),
        ('RI', 'River'),
    )
    water_body_type = models.CharField(
        max_length=2,
        choices=WATER_BODY_TYPE_CHOICES,
        default='RI', # River
    )

    # CHECK
    STATUS_CHOICES = (
        ('OP', 'Open'),
        ('CS', 'Coming Soon'),
        ('UM', 'Under Maintenance'),
        ('CD', 'Closed')
    )
    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='OP', # River
    )
    #status = models.CharField(max_length=200)

    date_added = models.DateField()
    sponsor_1 = models.ForeignKey(Sponsor, related_name = 'sponsorone', on_delete=models.SET_NULL, blank=True, null=True)
    sponsor_2 = models.ForeignKey(Sponsor, related_name = 'sponsortwo', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return "{} : {}".format(self.id, self.name)

class SMSContribution(models.Model):
    contributor_id = models.UUIDField()
    station = models.ForeignKey(Station, on_delete=models.PROTECT)
    water_height = models.FloatField()
    temperature = models.FloatField(null=True, blank=True, default=None)
    date_received = models.DateTimeField()

    class Meta:
            unique_together = ["contributor_id", "station", "water_height", "temperature", "date_received"]

    def __str__(self):
        return "{} : w={} t={} ({})".format(self.station_id, self.water_height, self.temperature, timezone.localtime(self.date_received).strftime('%D %H:%M:%S'))

class InvalidSMSContribution(models.Model):
    contributor_id = models.UUIDField()
    message_body = models.CharField(max_length=300)
    date_received = models.DateTimeField()

    class Meta:
            unique_together = ["contributor_id", "message_body", "date_received"]

    def __str__(self):
        return "{} ({})".format(self.message_body, timezone.localtime(self.date_received).strftime('%D %H:%M:%S'))

main_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
import os
from django.conf import settings
#from main_app import data_migrate_part_2_from_old_to_new
#from main_app import twilio_csv_data_migration

# Create your views here.
@login_required
def index(request):
    return render(request, 'main_app/index.html')

@login_required
def download(request):
    path = request.GET['path']
    file_path = os.path.join(settings.STATIC_DIR, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="text/csv")
            response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
            return response
    raise Http404

templates/main/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <!--<div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{url 'index'}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>-->
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/main_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'main_app:index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          {% else %}

          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/main_app/index.html
{% extends "main_app/base.html" %}

{% block body_block %}
{% load staticfiles %}

<div class="jumbotron">
  <h1>CrowdHydrology</h1>
</div>

<a href="{% url 'main_app:generate-graphs' %}" class="btn btn-primary" role="button">Generate Graphs & CSVs (5 min wait)</a>
<br><br>
<a href="https://plot.ly/~wafflez180/16/" target="_blank">contribution_amount_pie_chart</a><br>
<a href="https://plot.ly/~wafflez180/20" target="_blank">contribution_dates_line_graph</a><br>
<a href="{% url 'main_app:download' %}?path=stats/station_contribution_dict.csv" target="_blank">station_contribution_dict.csv</a><br>
<a href="{% url 'main_app:download' %}?path=stats/contrib_per_person_file.csv" target="_blank">contrib_per_person_file.csv</a><br>
<a href="{% url 'main_app:download' %}?path=stats/contrib_per_station_file.csv" target="_blank">contrib_per_station_file.csv</a>
<br>
<br>
<br>
<iframe width="900" height="800" frameborder="0" scrolling="no" src="//plot.ly/~wafflez180/16.embed"></iframe>
<iframe width="900" height="800" frameborder="0" scrolling="no" src="//plot.ly/~wafflez180/20.embed"></iframe>

{% endblock %}